# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='postReply',
            new_name='Repost',
        ),
    ]
