# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170614_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='SPW/SPWProject/post/static/post/postimages'),
        ),
    ]
