# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('proficPic', models.ImageField(upload_to=b'')),
                ('phoneNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
